# Histogram equalization
python main.py -i ImagesSet/histeq1.jpg -m Grayscale
python main.py -i ImagesSet/histeq2.jpg -m Grayscale
python main.py -i ImagesSet/histeq3.jpg -m Grayscale
python main.py -i ImagesSet/histeq4.jpg -m Grayscale
python main.py -i ImagesSet/histeq5.jpeg -m Grayscale
python main.py -i ImagesSet/histeq6.jpeg -m Grayscale
python main.py -i ImagesSet/histeq7.jpeg -m Grayscale
python main.py -i ImagesSet/histeq8.jpeg -m Grayscale
python main.py -i ImagesSet/histeq9.jpeg -m Grayscale
python main.py -i ImagesSet/histeq10.jpeg -m Grayscale
python main.py -i ImagesSet/histeq11.jpeg -m Grayscale
python main.py -i ImagesSet/histeq12.jpeg -m Grayscale
python main.py -i ImagesSet/histeq13.jpeg -m Grayscale
python main.py -i ImagesSet/histeq14.jpeg -m Grayscale
python main.py -i ImagesSet/histeqColor.jpg -m RGB
python main.py -i ImagesSet/histeqColor.jpg -m HSI
python main.py -i ImagesSet/histeqColor1.jpg -m RGB
python main.py -i ImagesSet/histeqColor1.jpg -m HSI
python main.py -i ImagesSet/histeqColor2.jpg -m RGB
python main.py -i ImagesSet/histeqColor2.jpg -m HSI
python main.py -i ImagesSet/histeqColor3.png -m RGB
python main.py -i ImagesSet/histeqColor3.png -m HSI
python main.py -i ImagesSet/histeqColor4.jpeg -m RGB
python main.py -i ImagesSet/histeqColor4.jpeg -m HSI
python main.py -i ImagesSet/histeqColor5.jpeg -m RGB
python main.py -i ImagesSet/histeqColor5.jpeg -m HSI
python main.py -i ImagesSet/histeqColor6.jpeg -m RGB
python main.py -i ImagesSet/histeqColor6.jpeg -m HSI
python main.py -i ImagesSet/histeqColor7.jpeg -m RGB
python main.py -i ImagesSet/histeqColor7.jpeg -m HSI
python main.py -i ImagesSet/histeqColor8.jpeg -m RGB
python main.py -i ImagesSet/histeqColor8.jpeg -m HSI
python main.py -i ImagesSet/histeqColor9.jpeg -m RGB
python main.py -i ImagesSet/histeqColor9.jpeg -m HSI
python main.py -i ImagesSet/histeqColor10.jpeg -m RGB
python main.py -i ImagesSet/histeqColor10.jpeg -m HSI
# Laplacian enhancement
python main.py -i ImagesSet/moon.tif -m LE 
python main.py -i ImagesSet/histeq5.jpeg -m LE
python main.py -i ImagesSet/histeq6.jpeg -m LE
python main.py -i ImagesSet/histeq7.jpeg -m LE
python main.py -i ImagesSet/histeq8.jpeg -m LE
python main.py -i ImagesSet/histeq9.jpeg -m LE
python main.py -i ImagesSet/histeq10.jpeg -m LE
python main.py -i ImagesSet/histeq11.jpeg -m LE
python main.py -i ImagesSet/histeq12.jpeg -m LE
python main.py -i ImagesSet/histeq13.jpeg -m LE
python main.py -i ImagesSet/histeq14.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor1.jpg -m LE
python main.py -i ImagesSet/intensity-histeqColor2.jpg -m LE
python main.py -i ImagesSet/intensity-histeqColor3.png -m LE
python main.py -i ImagesSet/intensity-histeqColor4.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor5.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor6.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor7.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor8.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor9.jpeg -m LE
python main.py -i ImagesSet/intensity-histeqColor10.jpeg -m LE

# Morphological transformation
python main.py -i ImagesSet/word_bw.bmp -m Erosion
python main.py -i ImagesSet/word_bw.bmp -m Dilation
python main.py -i ImagesSet/word_bw.bmp -m Closing
python main.py -i ImagesSet/word_bw.bmp -m Opening
python main.py -i ImagesSet/MT1.png -m Erosion
python main.py -i ImagesSet/MT1.png -m Dilation
python main.py -i ImagesSet/MT1.png -m Closing
python main.py -i ImagesSet/MT1.png -m Opening
python main.py -i ImagesSet/MT2.jpeg -m Erosion
python main.py -i ImagesSet/MT2.jpeg -m Dilation
python main.py -i ImagesSet/MT2.jpeg -m Closing
python main.py -i ImagesSet/MT2.jpeg -m Opening
python main.py -i ImagesSet/MT3.png -m Erosion
python main.py -i ImagesSet/MT3.png -m Dilation
python main.py -i ImagesSet/MT3.png -m Closing
python main.py -i ImagesSet/MT3.png -m Opening
python main.py -i ImagesSet/MT4.png -m Erosion
python main.py -i ImagesSet/MT4.png -m Dilation
python main.py -i ImagesSet/MT4.png -m Closing
python main.py -i ImagesSet/MT4.png -m Opening
python main.py -i ImagesSet/MT5.jpeg -m Erosion
python main.py -i ImagesSet/MT5.jpeg -m Dilation
python main.py -i ImagesSet/MT5.jpeg -m Closing
python main.py -i ImagesSet/MT5.jpeg -m Opening
python main.py -i ImagesSet/MT6.jpeg -m Erosion
python main.py -i ImagesSet/MT6.jpeg -m Dilation
python main.py -i ImagesSet/MT6.jpeg -m Closing
python main.py -i ImagesSet/MT6.jpeg -m Opening
python main.py -i ImagesSet/MT7.jpg -m Erosion
python main.py -i ImagesSet/MT7.jpg -m Dilation
python main.py -i ImagesSet/MT7.jpg -m Closing
python main.py -i ImagesSet/MT7.jpg -m Opening
python main.py -i ImagesSet/MT8.jpeg -m Erosion
python main.py -i ImagesSet/MT8.jpeg -m Dilation
python main.py -i ImagesSet/MT8.jpeg -m Closing
python main.py -i ImagesSet/MT8.jpeg -m Opening
python main.py -i ImagesSet/MT9.jpg -m Erosion
python main.py -i ImagesSet/MT9.jpg -m Dilation
python main.py -i ImagesSet/MT9.jpg -m Closing
python main.py -i ImagesSet/MT9.jpg -m Opening
python main.py -i ImagesSet/MT10.jpeg -m Erosion
python main.py -i ImagesSet/MT10.jpeg -m Dilation
python main.py -i ImagesSet/MT10.jpeg -m Closing
python main.py -i ImagesSet/MT10.jpeg -m Opening
python main.py -i ImagesSet/MT11.jpg -m Erosion
python main.py -i ImagesSet/MT11.jpg -m Dilation
python main.py -i ImagesSet/MT11.jpg -m Closing
python main.py -i ImagesSet/MT11.jpg -m Opening
python main.py -i ImagesSet/MT12.jpg -m Erosion
python main.py -i ImagesSet/MT12.jpg -m Dilation
python main.py -i ImagesSet/MT12.jpg -m Closing
python main.py -i ImagesSet/MT12.jpg -m Opening
python main.py -i ImagesSet/MT13.png -m Erosion
python main.py -i ImagesSet/MT13.png -m Dilation
python main.py -i ImagesSet/MT13.png -m Closing
python main.py -i ImagesSet/MT13.png -m Opening
python main.py -i ImagesSet/MT14.jpeg -m Erosion
python main.py -i ImagesSet/MT14.jpeg -m Dilation
python main.py -i ImagesSet/MT14.jpeg -m Closing
python main.py -i ImagesSet/MT14.jpeg -m Opening
python main.py -i ImagesSet/MT15.jpeg -m Erosion
python main.py -i ImagesSet/MT15.jpeg -m Dilation
python main.py -i ImagesSet/MT15.jpeg -m Closing
python main.py -i ImagesSet/MT15.jpeg -m Opening
python main.py -i ImagesSet/MT16.jpeg -m Erosion
python main.py -i ImagesSet/MT16.jpeg -m Dilation
python main.py -i ImagesSet/MT16.jpeg -m Closing
python main.py -i ImagesSet/MT16.jpeg -m Opening
python main.py -i ImagesSet/MT17.jpeg -m Erosion
python main.py -i ImagesSet/MT17.jpeg -m Dilation
python main.py -i ImagesSet/MT17.jpeg -m Closing
python main.py -i ImagesSet/MT17.jpeg -m Opening
python main.py -i ImagesSet/MT18.jpeg -m Erosion
python main.py -i ImagesSet/MT18.jpeg -m Dilation
python main.py -i ImagesSet/MT18.jpeg -m Closing
python main.py -i ImagesSet/MT18.jpeg -m Opening
python main.py -i ImagesSet/MT19.jpeg -m Erosion
python main.py -i ImagesSet/MT19.jpeg -m Dilation
python main.py -i ImagesSet/MT19.jpeg -m Closing
python main.py -i ImagesSet/MT19.jpeg -m Opening
python main.py -i ImagesSet/MT20.jpeg -m Erosion
python main.py -i ImagesSet/MT20.jpeg -m Dilation
python main.py -i ImagesSet/MT20.jpeg -m Closing
python main.py -i ImagesSet/MT20.jpeg -m Opening
